#' Check the balance of presences vs pseudoabsences among splits
#'
#' @param splits the data splits (an `rset` object), generated by a function such as
#' [spatialsample::spatial_block_cv()]
#' @param .col the column containing the presences
#' @returns a table of number of presences and pseudoabsences in the training and testing
#' set of each split
#' @export
#' @examples
#' lacerta_thin <- readRDS(system.file("extdata/lacerta_climate_sf.RDS",
#'   package = "tidysdm"
#' ))
#' lacerta_cv <- spatial_block_cv(lacerta_thin, v = 5)
#' check_splits_balance(lacerta_cv, class)
#'
check_splits_balance <- function(
    splits,
    .col) {
  .col <- rlang::enquo(.col) %>%
    rlang::quo_get_expr() %>%
    rlang::as_string()
  training_list <- lapply(splits$splits, function(x) {
    table(rsample::training(x) %>%
      sf::st_drop_geometry() %>% dplyr::pull(.col))
  })
  training_df <- do.call("rbind", training_list)
  dimnames(training_df)[[2]] <- paste0(dimnames(training_df)[[2]],"_train")
  testing_list <- lapply(splits$splits, function(x) {
    table(rsample::testing(x) %>%
            sf::st_drop_geometry() %>% dplyr::pull(.col))
  })
  testing_df <- do.call("rbind", testing_list)
  dimnames(testing_df)[[2]] <- paste0(dimnames(testing_df)[[2]],"_test")  
  balance_df <- cbind(training_df, testing_df)
  
  return(balance_df)
}
